# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d85ee3d5e5d52044bde393761fdba770d38f8d34c680c712ccb5c563c354f99fd89a85373417bfbaeca661da6d880e0302aa048c22a84fa7a6f6d1efd451e315

test:
  secret_key_base: ad4560230d08e03c2199adf35587d58c2e2d6eabafc7380a0c4d154d9fd43b555774d3b731446c2196a4595c16cd10fe37a6a46b7a33a4944574936597291aaa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
